services:
  # Web service for PHP application
  - type: web
    name: clothloop-backend
    env: docker
    rootDir: .
    region: ohio
    plan: free
    buildCommand: >
      apt-get update && apt-get install -y postgresql-client &&
      php -m | grep pgsql
    startCommand: >
      /usr/local/bin/wait-for-db.sh &&
      php setup_database.php &&
      apache2-foreground
    healthCheckPath: /api/system/db_diagnostics.php
    envVars:
      - key: RENDER
        value: true
      - key: FRONTEND_URL
        value: https://clothloop.vercel.app
      - key: DB_HOST
        fromDatabase:
          name: clothloop-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: clothloop-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: clothloop-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: clothloop-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  # PostgreSQL database
  - name: clothloop-db
    databaseName: clothloop
    plan: free
    type: postgres 